INSERT INTO Conference (name, edition, website, languages, begin, end, city, country, cfp, iso_country) VALUES ('JavaOne', 2017,'https://www.oracle.com/javaone/index.html', 'EN', DATE '2017-10-01', DATE '2017-10-05', 'San Francisco', 'U.S.A', DATE '2017-05-01','us');
INSERT INTO Conference (name, edition, website, languages, begin, end, city, country, iso_country) VALUES ('Java Forum Nord', 2018, 'http://javaforumnord.de', 'DE', DATE '2018-09-13', DATE '2018-09-13', 'Hannover', 'Germany','de');

INSERT INTO Conference (name,edition,  website, languages, begin, end, city, country, cfp, iso_country) VALUES ('Berlin Expert Days',2017, 'http://bed-con.org', 'DE, EN', DATE '2017-09-21', DATE '2017-09-22', 'Berlin', 'Germany', DATE '2017-05-15','de');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, cfp, iso_country) VALUES ('JUG Saxony Day',2017,'https://jug-saxony-day.org', 'DE ', DATE '2017-09-29', DATE '2017-09-29', 'Dresden', 'Germany', DATE '2017-04-23','de');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, cfp, iso_country) VALUES ('BaselOne',2017,'http://baselone.ch', 'DE, EN', DATE '2017-10-19', DATE '2017-10-19', 'Basel', 'Switzerland', DATE '2017-04-23','ch');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, cfp, iso_country) VALUES ('JavaZone',2017,'https://2017.javazone.no', 'EN', DATE '2017-09-13', DATE '2017-09-14', 'Oslo', 'Norway', DATE '2017-04-24','no');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('Spring I/O',2017,'http://2017.springio.net', 'EN', DATE '2017-05-18', DATE '2017-05-19', 'Barcelona', 'Spain','es');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('Devoxx UK',2017,'http://www.devoxx.co.uk', 'EN', DATE '2017-05-09', DATE '2017-05-11', 'London', 'UK','gb');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('Devoxx Poland',2017,'http://www.devoxx.pl', 'EN', DATE '2017-06-21', DATE '2017-06-23', 'Krakow', 'Poland','pl');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('Devoxx Morocco',2017,'http://www.devoxx.mo', 'EN', DATE '2017-11-14', DATE '2017-11-16', 'Casablanca', 'Morocco','ma');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('Devoxx Belgium',2018,'http://www.devoxx.be', 'EN', DATE '2018-11-12', DATE '2018-11-16', 'Antwerp', 'Belgium','be');

INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('Riga Dev Days',2017,'http://rigadevdays.lv/', 'EN', DATE '2017-05-15', DATE '2017-05-17', 'Riga', 'Latvia', 'lv');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('DevDays Vilnius',2018,'http://devdays.lt/', 'EN', DATE '2018-05-29', DATE '2018-05-31', 'Vilnius', 'Lithuania','lt');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('JBCNConf 2017',2017,'http://www.jbcnconf.com', 'EN', DATE '2017-06-19', DATE '2017-06-21', 'Barcelona', 'Spain','es');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('jPrime',2018,'http://jprime.io/', 'EN', DATE '2018-05-29', DATE '2018-05-30', 'Sofia', 'Bulgaria', 'bg');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('J On The Beach',2018,'https://jonthebeach.com/', 'EN', DATE '2018-05-23', DATE '2018-05-25', 'Malaga', 'Spain', 'es');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country) VALUES ('J On The Beach',2019,'https://jonthebeach.com/', 'EN', DATE '2019-05-23', DATE '2019-05-25', 'Malaga', 'Spain', 'es');
INSERT INTO Conference (name,edition, website, languages, begin, end, city, country, iso_country)VALUES ('Uphill Conf',2019,'https://uphillconf.com/', 'EN', DATE '2019-05-02', DATE '2019-05-03', 'Bern', 'Switzerland', 'ch');
